PR #56154: Unbreak windows build
Imported from GitHub PR https://github.com/tensorflow/tensorflow/pull/56154

Address two build problem when building jaxlib for windows.

@hawkinsp
Copybara import of the project:

--
def2a1cf086613a97438156c59d8b4e972eb70b7 by Cloud Han <cloudhan@outlook.com>:

Avoid using init-statements in if

Otherwise,

    error C2429: language feature 'init-statements in if/switch' requires compiler flag '/std:c++17'

will be triggered when building jaxlib with MSVC

--
df137290aef8847d1c50caed1fe762b374ef1390 by Cloud Han <cloudhan@outlook.com>:

Avoid including `Python.h` before `pybind11.h`

As of https://github.com/llvm/llvm-project/commit/784a5bccfd, llvm
specially handles Python.h, in short, 'always included after pybind11'.

Otherwise, redefinition of PyObject.

Merging this change closes #56154

PiperOrigin-RevId: 449478348